### ISSUE TITLE
Game of Thrones Dubrovnik Film Locations Missing

### ISSUE THREAD

**Issue by RusseII** [mroseman95/FilmLocations#2]
+
−
Leaflet | © Stadia Maps, © OpenMapTiles © OpenStreetMap contributors
Star Wars: Episode VIII - The Last Jedi
Dubrovnik, Croatia
City of Canto Bright
Robin Hood
Dubrovnik, Croatia
location
Fan
Dubrovnik, Croatia
location
Fiddler on the Roof
Mala, Croatia
Captain America
Dubrovnik, Croatia
The Secret Invasion
Dubrovnik, Croatia, Yugoslavia
Occupation in 26 Pictures
Dubrovnik, Croatia
Hajde da se volimo
Dubrovnik, Croatia
Goya - oder Der arge Weg der Erkenntnis
Dubrovnik, Croatia, Yugoslavia
Cure: The Life of Another
Dubrovnik, Croatia
Her Harem
Dubrovnik, Croatia
during holiday
Kommissar X - Jagd auf Unbekannt
Dubrovnik, Croatia
Shadow of Treason
Dubrovnik, Croatia, Yugoslavia
The Demolition Squad
Dubrovnik, Croatia, Yugoslavia
The Lion Is Ready to Jump
Dubrovnik, Croatia, Yugoslavia
Libertas
Dubrovnik, Croatia
Die blutigen Geier von Alaska
Dubrovnik, Croatia
Portrait in Terror
Dubrovnik, Croatia
A Dangerous Game
Dubrovnik, Croatia

No game of thrones :(

**Comment by mroseman95** [comment]
currently It's just films. I get the locations by scraping IMDb, and they have TV locations as well, so in the future I might add TV shows to the app, or make a sibling website that's just TV show locations.
